import ExcelJS from "exceljs";

export const MAX_STOCK_UPLOAD_BYTES = 5 * 1024 * 1024;
export const MAX_STOCK_ROWS = 5000;

const COLUMNS = {
  itemName: ["item name"],
  qty: ["total stock"],
  company: ["company name"],
  genericName: ["generic name"],
  category: ["item category"],
  itemType: ["item type"],
  purchaseTotal: ["p.ratetot", "p.rate tot", "p rate tot"],
  landingTotal: ["lp.ratetot", "lp.rate tot", "lp rate tot"],
  saleTotal: ["s.ratetot", "s.rate tot", "s rate tot"],
};

const REQUIRED = ["itemName", "qty"];

const EMPTY_VALUES = new Set(["", "NA", "N/A", "NOT AVAILABLE", "-", "—"]);

const parseError = (message) => Object.assign(new Error(message), { status: 400 });

export const stockItemKey = (name) =>
  String(name ?? "")
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase();

const cellValue = (cell) => {
  const v = cell?.value;
  if (v && typeof v === "object") {
    if ("result" in v) return v.result;
    if ("richText" in v) return v.richText.map((t) => t.text).join("");
    if ("text" in v) return v.text;
  }
  return v;
};

const text = (v) => {
  if (v === null || v === undefined) return null;
  const s = String(v).replace(/\s+/g, " ").trim();
  return EMPTY_VALUES.has(s.toUpperCase()) ? null : s;
};

const number = (v) => {
  if (v === null || v === undefined || v === "") return null;
  if (typeof v === "number") return Number.isFinite(v) ? v : NaN;
  const cleaned = String(v).replace(/[,₹\s]/g, "");
  if (cleaned === "") return null;
  const n = Number(cleaned);
  return Number.isFinite(n) ? n : NaN;
};

const round2 = (n) => (n === null ? null : Math.round(n * 100) / 100);

const GENERATED =
  /GENERATED BY:\s*(.*?)\s*\[(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)?\]/i;

function generatedFrom(line) {
  const m = GENERATED.exec(line);
  if (!m) return null;
  const [, by, dd, mm, yyyy, hh, min, ss = "0", ampm] = m;
  let hour = Number(hh);
  if (ampm) hour = (hour % 12) + (ampm.toUpperCase() === "PM" ? 12 : 0);
  const pad = (n) => String(n).padStart(2, "0");
  const iso = `${yyyy}-${pad(mm)}-${pad(dd)}T${pad(hour)}:${pad(min)}:${pad(ss)}+05:30`;
  const at = new Date(iso);
  return { by: by || null, at: Number.isNaN(at.getTime()) ? null : at.toISOString() };
}

function headerMap(row) {
  const found = {};
  row.eachCell({ includeEmpty: false }, (cell, col) => {
    const label = String(cellValue(cell) ?? "")
      .trim()
      .toLowerCase();
    for (const [field, names] of Object.entries(COLUMNS)) {
      if (!found[field] && names.includes(label)) found[field] = col;
    }
  });
  return found;
}

export async function parseStockReport(buffer) {
  const workbook = new ExcelJS.Workbook();
  try {
    await workbook.xlsx.load(buffer);
  } catch {
    throw parseError("This file could not be opened. Upload the stock report as an .xlsx file.");
  }
  const ws = workbook.worksheets.find((sheet) => sheet.actualRowCount > 0);
  if (!ws) throw parseError("The file has no data in it.");

  const meta = { storeName: null, generatedBy: null, reportGeneratedAt: null };
  let columns = null;
  let headerRow = 0;
  for (let r = 1; r <= Math.min(ws.rowCount, 30) && !columns; r++) {
    const row = ws.getRow(r);
    const first = String(cellValue(row.getCell(1)) ?? "").trim();
    if (/^STORE NAME:/i.test(first)) meta.storeName = text(first.replace(/^STORE NAME:/i, ""));
    const generated = generatedFrom(first);
    if (generated) {
      meta.generatedBy = generated.by;
      meta.reportGeneratedAt = generated.at;
    }
    const map = headerMap(row);
    if (REQUIRED.every((f) => map[f])) {
      columns = map;
      headerRow = r;
    }
  }
  if (!columns) {
    throw parseError(
      'Could not find the header row. The sheet needs "Item name" and "Total Stock" columns — upload the DARPAN Item Wise Stock Report.',
    );
  }

  const byKey = new Map();
  const skipped = [];
  for (let r = headerRow + 1; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    const get = (field) => (columns[field] ? cellValue(row.getCell(columns[field])) : null);
    const name = text(get("itemName"));
    if (!name || /^TOTAL$/i.test(name)) continue;
    if (byKey.size >= MAX_STOCK_ROWS) {
      throw parseError(
        `The sheet has more than ${MAX_STOCK_ROWS} items; split it into smaller files.`,
      );
    }
    const qty = number(get("qty"));
    if (qty === null || Number.isNaN(qty)) {
      skipped.push({ row: r, itemName: name, reason: "Total Stock is not a number" });
      continue;
    }
    const purchaseTotal = number(get("purchaseTotal"));
    const landingTotal = number(get("landingTotal"));
    const saleTotal = number(get("saleTotal"));
    const line = {
      rowNo: r,
      itemKey: stockItemKey(name),
      itemName: name,
      qty,
      company: text(get("company")),
      genericName: text(get("genericName")),
      category: text(get("category")),
      itemType: text(get("itemType")),
      purchaseTotal: Number.isNaN(purchaseTotal) ? null : purchaseTotal,
      landingTotal: Number.isNaN(landingTotal) ? null : landingTotal,
      saleTotal: Number.isNaN(saleTotal) ? null : saleTotal,
      warnings: [],
    };
    const existing = byKey.get(line.itemKey);
    if (existing) {
      existing.qty += line.qty;
      for (const f of ["purchaseTotal", "landingTotal", "saleTotal"]) {
        if (line[f] !== null) existing[f] = (existing[f] ?? 0) + line[f];
      }
      if (!existing.warnings.includes("listed more than once — quantities added"))
        existing.warnings.push("listed more than once — quantities added");
      continue;
    }
    byKey.set(line.itemKey, line);
  }

  const lines = [...byKey.values()].map((l) => {
    if (l.qty < 0) l.warnings.push("negative stock");
    if (l.qty > 0 && l.saleTotal > 0 && l.purchaseTotal !== null && l.purchaseTotal / l.qty < 0.05)
      l.warnings.push("purchase rate is almost zero");
    if (l.qty > 0 && !l.saleTotal) l.warnings.push("no sale rate");
    return {
      ...l,
      qty: round2(l.qty),
      purchaseTotal: round2(l.purchaseTotal),
      landingTotal: round2(l.landingTotal),
      saleTotal: round2(l.saleTotal),
    };
  });
  if (!lines.length) throw parseError("The sheet has no stock items under the header row.");

  return { meta, lines, skipped };
}
