import { test, expect, request } from "@playwright/test";
import ExcelJS from "exceljs";
import { one, query } from "../helpers/db.mjs";
import { apiAs } from "../helpers/auth.mjs";
import { PIN } from "../fixtures/data.mjs";
import { API_URL } from "../setup/testEnv.mjs";
import { assertTestDatabase } from "../setup/guard.mjs";

if (process.env.DATABASE_URL) assertTestDatabase(process.env.DATABASE_URL);

const PHARMACY_ADMIN = { id: 9301, name: "E2E Pharmacy Admin", role: "pharmacy_admin" };
const PHARMACY = { id: 9302, name: "E2E Pharmacy", role: "pharmacy" };
const TAG = `PH01${Date.now().toString(36).toUpperCase()}`;
const name = (n) => `${TAG} ${n}`;

async function stockSheet(items, generated = "05/10/2026 01:12:35 PM") {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet("Stock report");
  ws.addRow(["ITEM WISE STOCK REPORT"]);
  ws.addRow([`GENERATED BY: DARPAN [${generated}]`]);
  ws.addRow(["STORE NAME: GINI HEALTH INDIA PVT LTD"]);
  ws.addRow([]);
  ws.addRow([
    "Item name",
    "Total Stock",
    "Company Name",
    "Generic Name",
    "Item Category",
    "Item Sub Category",
    "Item Type",
    "Schedule Drug",
    "Location",
    "P.RateTot",
    "LP.RateTot",
    "S.RateTot",
    "PTR wise Diff",
    "LP wise Diff",
  ]);
  for (const i of items) {
    ws.addRow([
      i.name,
      i.qty,
      i.company ?? null,
      "NA",
      "TAB",
      null,
      null,
      null,
      null,
      i.p,
      i.p,
      i.s,
    ]);
  }
  ws.addRow([]);
  ws.addRow(["TOTAL", null, null, null, null, null, null, null, null, 1, 1, 1]);
  return Buffer.from(await wb.xlsx.writeBuffer());
}

async function login(user) {
  const anon = await request.newContext({ baseURL: API_URL });
  const res = await anon.post("/api/auth/login", { data: { doctor_id: user.id, pin: PIN } });
  const body = await res.json();
  await anon.dispose();
  if (!res.ok()) throw new Error(`login ${user.role}: ${body.error}`);
  return request.newContext({
    baseURL: API_URL,
    extraHTTPHeaders: { Authorization: `Bearer ${body.access_token}` },
  });
}

const upload = (api, buffer, fileName = "stock.xlsx") =>
  api.post(`/api/pharmacy/stock/uploads?fileName=${encodeURIComponent(fileName)}`, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    },
    data: buffer,
  });

async function cleanUp() {
  await query(`DELETE FROM pharmacy_inventory WHERE medicine_name LIKE $1`, [`${TAG}%`]);
  await query(`DELETE FROM pharmacy_stock_items WHERE item_key LIKE $1`, [`${TAG}%`]);
}

let admin;
let pharmacy;

test.describe.serial("PH01 pharmacy stock upload", () => {
  test.beforeAll(async () => {
    for (const u of [PHARMACY_ADMIN, PHARMACY]) {
      await query(
        `INSERT INTO doctors (id, name, short_name, role, pin, is_active)
         VALUES ($1, $2, $2, $3, $4, TRUE)
         ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role, is_active = TRUE`,
        [u.id, u.name, u.role, PIN],
      );
    }
    await query(`UPDATE pharmacy_stock_uploads SET status = 'discarded' WHERE status = 'preview'`);
    await query(
      `UPDATE pharmacy_stock_uploads SET report_generated_at = NULL WHERE status = 'committed'`,
    );
    await query(`UPDATE pharmacy_stock_items SET qty = 0 WHERE item_key NOT LIKE $1`, [`${TAG}%`]);
    admin = await login(PHARMACY_ADMIN);
    pharmacy = await login(PHARMACY);
  });

  test.afterAll(async () => {
    await cleanUp();
    await admin?.dispose();
    await pharmacy?.dispose();
  });

  test("1. pharmacy staff can view but not upload, and see no purchase rates", async () => {
    const view = await pharmacy.get("/api/pharmacy/stock/summary");
    expect(view.ok()).toBe(true);
    expect(await view.json()).not.toHaveProperty("purchaseValue");
    const refused = await upload(
      pharmacy,
      await stockSheet([{ name: name("X"), qty: 1, p: 1, s: 2 }]),
    );
    expect(refused.status()).toBe(403);
    const reception = await apiAs("reception");
    expect((await reception.get("/api/pharmacy/stock")).status()).toBe(403);
    await reception.dispose();
  });

  test("2. a bad file is refused with a readable reason", async () => {
    const res = await upload(admin, Buffer.from("not a spreadsheet"));
    expect(res.status()).toBe(400);
    expect((await res.json()).error).toMatch(/xlsx/);
  });

  test("3. preview shows new items and changes nothing until applied", async () => {
    const res = await upload(
      admin,
      await stockSheet([
        { name: name("ALPHA 10 TAB 1*10"), qty: 20, p: 100, s: 200 },
        { name: name("BETA 5MG TAB"), qty: 5, p: 50, s: 75 },
        { name: name("BETA 5MG TAB"), qty: 3, p: 30, s: 45 },
      ]),
    );
    expect(res.ok()).toBe(true);
    const preview = await res.json();
    expect(preview.status).toBe("preview");
    expect(preview.storeName).toBe("GINI HEALTH INDIA PVT LTD");
    expect(preview.itemCount).toBe(2);
    expect(preview.totalUnits).toBe(28);
    expect(preview.diff.added.map((a) => a.itemName).sort()).toEqual([
      name("ALPHA 10 TAB 1*10"),
      name("BETA 5MG TAB"),
    ]);
    expect(preview.warnings.some((w) => /more than once/.test(w.message))).toBe(true);
    const items = await one(
      `SELECT COUNT(*)::int AS n FROM pharmacy_stock_items WHERE item_key LIKE $1`,
      [`${TAG}%`],
    );
    expect(items.n).toBe(0);

    const applied = await admin.post(`/api/pharmacy/stock/uploads/${preview.id}/commit`);
    expect(applied.ok()).toBe(true);
    expect((await applied.json()).status).toBe("committed");

    const beta = await one(
      `SELECT stock_qty, price_per_unit, source FROM pharmacy_inventory WHERE medicine_name = $1`,
      [name("BETA 5MG TAB")],
    );
    expect(beta).toMatchObject({ stock_qty: 8, source: "darpan" });
    expect(Number(beta.price_per_unit)).toBe(15);
  });

  test("4. an item missing from the next sheet goes out of stock", async () => {
    const res = await upload(
      admin,
      await stockSheet(
        [{ name: name("ALPHA 10 TAB 1*10"), qty: 12, p: 60, s: 120 }],
        "05/10/2026 05:00:00 PM",
      ),
    );
    const preview = await res.json();
    expect(preview.diff.changed).toEqual([
      expect.objectContaining({ itemName: name("ALPHA 10 TAB 1*10"), oldQty: 20, newQty: 12 }),
    ]);
    expect(preview.diff.goingOut.map((g) => g.itemName)).toEqual([name("BETA 5MG TAB")]);
    expect((await admin.post(`/api/pharmacy/stock/uploads/${preview.id}/commit`)).ok()).toBe(true);

    const beta = await one(`SELECT stock_qty FROM pharmacy_inventory WHERE medicine_name = $1`, [
      name("BETA 5MG TAB"),
    ]);
    expect(beta.stock_qty).toBe(0);
  });

  test("5. an older report cannot overwrite a newer one", async () => {
    const res = await upload(
      admin,
      await stockSheet(
        [{ name: name("ALPHA 10 TAB 1*10"), qty: 99, p: 1, s: 2 }],
        "01/10/2026 09:00:00 AM",
      ),
    );
    const preview = await res.json();
    const refused = await admin.post(`/api/pharmacy/stock/uploads/${preview.id}/commit`);
    expect(refused.status()).toBe(409);
    expect((await refused.json()).error).toMatch(/newer stock report/);
    await admin.post(`/api/pharmacy/stock/uploads/${preview.id}/discard`);
  });

  test("6. linking a prescription name puts the stock under that name", async () => {
    const key = encodeURIComponent(name("ALPHA 10 TAB 1*10"));
    const linked = await admin.post(`/api/pharmacy/stock/items/${key}/links`, {
      data: { medicineName: `Tab ${name("Alpha 10")}` },
    });
    expect(linked.ok()).toBe(true);
    const body = await linked.json();
    expect(body.links.map((l) => l.medicineKey)).toContain(name("ALPHA 10"));

    const row = await one(`SELECT stock_qty FROM pharmacy_inventory WHERE medicine_name = $1`, [
      name("ALPHA 10"),
    ]);
    expect(row.stock_qty).toBe(12);

    const removed = await admin.delete(
      `/api/pharmacy/stock/items/${key}/links/${encodeURIComponent(name("ALPHA 10"))}`,
    );
    expect(removed.ok()).toBe(true);
    const gone = await query(`SELECT 1 FROM pharmacy_inventory WHERE medicine_name = $1`, [
      name("ALPHA 10"),
    ]);
    expect(gone.rowCount).toBe(0);
  });

  test("7. the stock list hides purchase rates from pharmacy staff only", async () => {
    const q = encodeURIComponent(TAG);
    const forAdmin = await (await admin.get(`/api/pharmacy/stock?q=${q}`)).json();
    const forPharmacy = await (await pharmacy.get(`/api/pharmacy/stock?q=${q}`)).json();
    expect(forAdmin.items[0]).toHaveProperty("purchaseTotal");
    expect(forPharmacy.items[0]).not.toHaveProperty("purchaseTotal");
    expect(forPharmacy.total).toBe(2);
  });
});
