// Physical examination section definitions
export const EXAM_SECTIONS = {
  General: [
    {
      id: "gen",
      l: "General",
      ic: "👤",
      o: [
        "Well-built",
        "Obese",
        "Thin",
        "Pale",
        "Icteric",
        "Cyanosed",
        "Clubbing",
        "Lymphadenopathy",
        "Edema",
      ],
    },
    {
      id: "skin",
      l: "Skin",
      ic: "🖐️",
      o: [
        "Normal",
        "Acanthosis Nigricans",
        "Shin Spots",
        "Dry",
        "Xanthoma",
        "Candidiasis",
        "Skin Tags",
      ],
    },
    {
      id: "eyes",
      l: "Eyes",
      ic: "👁️",
      o: [
        "Normal",
        "Pallor",
        "Xanthelasma",
        "Icterus",
        "Fundus Normal",
        "DR Background",
        "DR Proliferative",
      ],
    },
    {
      id: "neck",
      l: "Neck",
      ic: "🦋",
      o: [
        "Normal",
        "Goitre Gr1",
        "Goitre Gr2",
        "Goitre Gr3",
        "Acanthosis",
        "Skin Tags",
        "Thyroid Nodule",
      ],
    },
    {
      id: "cvs",
      l: "CVS",
      ic: "💓",
      o: ["S1S2 Normal", "Murmur", "Irregular Rhythm", "Raised JVP", "Displaced Apex"],
    },
    {
      id: "resp",
      l: "Respiratory",
      ic: "🌬️",
      o: ["BAEL", "Wheeze", "Crepitations", "Rhonchi", "Reduced Air Entry", "Pleural Effusion"],
    },
    {
      id: "abd",
      l: "Abdomen",
      ic: "🫃",
      o: ["Soft NT", "Striae", "Hepatomegaly", "Splenomegaly", "Ascites", "Tenderness"],
    },
    {
      id: "cns",
      l: "CNS",
      ic: "🧠",
      o: ["Alert Oriented", "Confused", "Focal Deficit", "DTR Normal", "DTR Reduced", "DTR Absent"],
    },
    {
      id: "limb",
      l: "Lower Limb",
      ic: "🦵",
      o: ["Normal", "Edema Pitting", "Shin Spots", "Hair Loss", "Varicose Veins", "DVT Signs"],
    },
    {
      id: "foot",
      l: "Diabetic Foot",
      ic: "🦶",
      o: [
        "Normal",
        "Dry",
        "Calluses",
        "Fissures",
        "Ulcer Active",
        "Ulcer Healed",
        "Charcot",
        "Monofilament Reduced",
        "Vibration Reduced",
      ],
    },
  ],
  Ortho: [
    {
      id: "knee",
      l: "Knee",
      ic: "🦵",
      o: [
        "Normal ROM",
        "Restricted",
        "Crepitus",
        "Effusion",
        "Varus",
        "Valgus",
        "Lachman+",
        "McMurray+",
        "Drawer+",
      ],
    },
    {
      id: "hip",
      l: "Hip",
      ic: "🦴",
      o: ["Normal ROM", "Restricted IR", "Restricted ER", "Trendelenburg+", "FABER+"],
    },
    {
      id: "shoulder",
      l: "Shoulder",
      ic: "💪",
      o: ["Normal ROM", "Restricted Abduction", "Impingement+", "Neer+", "Hawkins+", "Drop Arm+"],
    },
    {
      id: "spine",
      l: "Spine",
      ic: "🏋️",
      o: ["Normal", "Kyphosis", "Scoliosis", "Tenderness", "SLR+", "SLRT+", "Muscle Spasm"],
    },
    {
      id: "wrist",
      l: "Wrist/Hand",
      ic: "✋",
      o: ["Normal", "Tinel+", "Phalen+", "Deformity", "Swelling", "Trigger Finger"],
    },
  ],
  Pulmo: [
    {
      id: "ausc",
      l: "Auscultation",
      ic: "🫁",
      o: [
        "Clear Bilateral",
        "Wheeze",
        "Fine Crepts",
        "Coarse Crepts",
        "Rhonchi",
        "Stridor",
        "Reduced BS",
      ],
    },
    {
      id: "pattern",
      l: "Breathing",
      ic: "🌬️",
      o: ["Normal", "Tachypnea", "Bradypnea", "Kussmaul", "Cheyne-Stokes", "Orthopnea"],
    },
    {
      id: "chest",
      l: "Chest",
      ic: "🫁",
      o: ["Normal", "Barrel Chest", "Pigeon Chest", "Asymmetric", "Intercostal Recession"],
    },
    {
      id: "perc",
      l: "Percussion",
      ic: "🔔",
      o: ["Resonant", "Dull", "Stony Dull", "Hyper-resonant"],
    },
  ],
  Cardio: [
    {
      id: "pulse",
      l: "Pulse",
      ic: "💓",
      o: [
        "Regular",
        "Irregularly Irregular",
        "Regularly Irregular",
        "Bounding",
        "Thready",
        "Radio-femoral Delay",
      ],
    },
    { id: "jvp", l: "JVP", ic: "🔺", o: ["Normal", "Raised", "Not Visible", "Kussmaul Sign+"] },
    {
      id: "prec",
      l: "Precordium",
      ic: "❤️",
      o: [
        "Apex Normal",
        "Apex Displaced",
        "Thrill",
        "Heave",
        "S1S2 Normal",
        "S3 Gallop",
        "S4 Gallop",
        "Murmur Systolic",
        "Murmur Diastolic",
      ],
    },
    {
      id: "periph",
      l: "Peripheral",
      ic: "🦵",
      o: ["Normal", "Pedal Edema", "Sacral Edema", "Calf Tenderness", "Varicose Veins"],
    },
  ],
};
