export const ROUTE_MAP = {
  home: "/",
  dashboard: "/dashboard",
  quick: "/quick",
  patient: "/patient",
  intake: "/intake",
  fu_load: "/fu-load",
  fu_review: "/fu-review",
  fu_edit: "/fu-edit",
  fu_symptoms: "/fu-symptoms",
  fu_gen: "/fu-gen",
  hxclinical: "/history-clinical",
  exam: "/exam",
  assess: "/assess",
  vitals: "/vitals",
  mo: "/mo",
  consultant: "/consultant",
  plan: "/plan",
  docs: "/docs",
  messages: "/messages",
  labportal: "/lab-portal",
  history: "/history",
  outcomes: "/outcomes",
  ai: "/ai",
  reports: "/reports",
  ci: "/ci",
};
