ALTER TABLE giniflow_visits
  ADD COLUMN IF NOT EXISTS echo_referral BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS echo_handed_over_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS echo_handed_over_by INT REFERENCES doctors(id) ON DELETE SET NULL;
