// Canonical name mapping for lab results — ensures consistent names across all routes
// so outcomes page, visit page, and OPD page all show the same data.
const CANONICAL_MAP = {
  hba1c: "HbA1c",
  "glycated hemoglobin": "HbA1c",
  a1c: "HbA1c",
  "glycated haemoglobin": "HbA1c",
  fbs: "FBS",
  "fasting glucose": "FBS",
  "fasting blood sugar": "FBS",
  fpg: "FBS",
  "fasting plasma glucose": "FBS",
  ldl: "LDL",
  "ldl cholesterol": "LDL",
  "ldl-c": "LDL",
  "ldl cholesterol-direct": "LDL",
  hdl: "HDL",
  "hdl cholesterol": "HDL",
  triglycerides: "Triglycerides",
  tg: "Triglycerides",
  creatinine: "Creatinine",
  "s.creatinine": "Creatinine",
  "serum creatinine": "Creatinine",
  egfr: "eGFR",
  gfr: "eGFR",
  "estimated gfr": "eGFR",
  tsh: "TSH",
  "thyroid stimulating hormone": "TSH",
  haemoglobin: "Haemoglobin",
  hemoglobin: "Haemoglobin",
  hb: "Haemoglobin",
  uacr: "UACR",
  "urine acr": "UACR",
  microalbumin: "UACR",
  "vitamin d": "Vitamin D",
  "25-oh vitamin d": "Vitamin D",
  "vit d": "Vitamin D",
  "vitamin b12": "Vitamin B12",
  b12: "Vitamin B12",
  "sgpt (alt)": "SGPT (ALT)",
  alt: "SGPT (ALT)",
  sgpt: "SGPT (ALT)",
  "sgot (ast)": "SGOT (AST)",
  ast: "SGOT (AST)",
  sgot: "SGOT (AST)",
  ppbs: "PPBS",
  "post prandial": "PPBS",
  ferritin: "Ferritin",
  "s. ferritin": "Ferritin",
  "s.ferritin": "Ferritin",
  "serum ferritin": "Ferritin",
  crp: "CRP",
  alp: "ALP",
  "non-hdl": "Non-HDL",
  "non hdl": "Non-HDL",
  t3: "T3",
  "total t3": "T3",
  t4: "T4",
  "total t4": "T4",
  "free t4": "T4",
  weight: "Weight",
  "weight (kg)": "Weight",
  "body weight": "Weight",
  bmi: "BMI",
  "body mass index": "BMI",
  "bmi (kg/m2)": "BMI",
  "bmi (kg/m²)": "BMI",
  sbp: "Systolic BP",
  "systolic bp": "Systolic BP",
  "systolic blood pressure": "Systolic BP",
  dbp: "Diastolic BP",
  "diastolic bp": "Diastolic BP",
  "diastolic blood pressure": "Diastolic BP",
  "waist circumference": "Waist",
  "waist (cm)": "Waist",
  waist: "Waist",
  "uric acid": "Uric Acid",
  "serum uric acid": "Uric Acid",
  "total cholesterol": "Total Cholesterol",
  cholesterol: "Total Cholesterol",
  "direct ldl": "LDL",
  "total protein": "Total Protein",
  albumin: "Albumin",
  calcium: "Calcium",
  sodium: "Sodium",
  potassium: "Potassium",
  "blood urea nitrogen": "BUN",
  bun: "BUN",
  urea: "Urea",
  "blood urea": "Urea",
  glucose: "FBS",
  "random blood sugar": "RBS",
  rbs: "RBS",
  "pp blood sugar": "PPBS",
  "2 hour ppbs": "PPBS",
  "pro-bnp": "Pro-BNP",
  probnp: "Pro-BNP",
  "nt-probnp": "Pro-BNP",
  "nt pro bnp": "Pro-BNP",
  "hs-crp": "hs-CRP",
  "high sensitivity crp": "hs-CRP",
  hscrp: "hs-CRP",
  iron: "Iron",
  "serum iron": "Iron",
  "total iron binding capacity": "TIBC",
  tibc: "TIBC",
  "transferrin saturation": "Transferrin Saturation",
  "% transferrin saturation": "Transferrin Saturation",
  acr: "UACR",
  "urine albumin creatinine ratio": "UACR",
  "microalbumin/creatinine": "UACR",
  wbc: "WBC",
  "white blood cells": "WBC",
  "total wbc": "WBC",
  rbc: "RBC",
  "red blood cells": "RBC",
  platelets: "Platelets",
  "platelet count": "Platelets",
};

function stripEmbeddedDate(str) {
  return str.replace(/\s*\(\d{1,2}\/\d{1,2}\/\d{2,4}\)\s*$/i, "").trim();
}

// Strips "Serum", "S.", "Sr.", "B." lab-report prefixes so variants like
// "S. Ferritin" and "Serum Calcium" collapse onto the same canonical name.
function stripReportPrefix(str) {
  return str.replace(/^(serum|plasma|s\.?|sr\.?|b\.?)\s+/i, "").trim();
}

export const getCanonical = (name) => {
  const cleaned = stripEmbeddedDate((name || "").trim()).toLowerCase();
  if (CANONICAL_MAP[cleaned]) return CANONICAL_MAP[cleaned];
  const stripped = stripReportPrefix(cleaned);
  return CANONICAL_MAP[stripped] || null;
};
