// Canonical name mapping for lab results — ensures consistent names across all routes
// so outcomes page, visit page, and OPD page all show the same data.
const CANONICAL_MAP = {
  hba1c: "HbA1c",
  "glycated hemoglobin": "HbA1c",
  a1c: "HbA1c",
  "glycated haemoglobin": "HbA1c",
  fbs: "FBS",
  "fasting glucose": "FBS",
  "fasting blood sugar": "FBS",
  fpg: "FBS",
  "fasting plasma glucose": "FBS",
  ldl: "LDL",
  "ldl cholesterol": "LDL",
  "ldl-c": "LDL",
  "ldl cholesterol-direct": "LDL",
  hdl: "HDL",
  "hdl cholesterol": "HDL",
  triglycerides: "Triglycerides",
  tg: "Triglycerides",
  creatinine: "Creatinine",
  "s.creatinine": "Creatinine",
  "serum creatinine": "Creatinine",
  egfr: "eGFR",
  gfr: "eGFR",
  "estimated gfr": "eGFR",
  tsh: "TSH",
  "thyroid stimulating hormone": "TSH",
  haemoglobin: "Haemoglobin",
  hemoglobin: "Haemoglobin",
  hb: "Haemoglobin",
  uacr: "UACR",
  "urine acr": "UACR",
  microalbumin: "UACR",
  "vitamin d": "Vitamin D",
  "25-oh vitamin d": "Vitamin D",
  "vit d": "Vitamin D",
  "vitamin b12": "Vitamin B12",
  b12: "Vitamin B12",
  "sgpt (alt)": "SGPT (ALT)",
  alt: "SGPT (ALT)",
  sgpt: "SGPT (ALT)",
  "sgot (ast)": "SGOT (AST)",
  ast: "SGOT (AST)",
  sgot: "SGOT (AST)",
  ppbs: "PPBS",
  "post prandial": "PPBS",
  ferritin: "Ferritin",
  "s. ferritin": "Ferritin",
  "s.ferritin": "Ferritin",
  "serum ferritin": "Ferritin",
  crp: "CRP",
  alp: "ALP",
  "non-hdl": "Non-HDL",
  "non hdl": "Non-HDL",
  t3: "T3",
  "total t3": "T3",
  t4: "T4",
  "total t4": "T4",
  "free t4": "T4",
  weight: "Weight",
  "weight (kg)": "Weight",
  "body weight": "Weight",
  bmi: "BMI",
  "body mass index": "BMI",
  "bmi (kg/m2)": "BMI",
  "bmi (kg/m²)": "BMI",
  sbp: "Systolic BP",
  "systolic bp": "Systolic BP",
  "systolic blood pressure": "Systolic BP",
  dbp: "Diastolic BP",
  "diastolic bp": "Diastolic BP",
  "diastolic blood pressure": "Diastolic BP",
  "waist circumference": "Waist",
  "waist (cm)": "Waist",
  waist: "Waist",
  "uric acid": "Uric Acid",
  "serum uric acid": "Uric Acid",
  "total cholesterol": "Total Cholesterol",
  cholesterol: "Total Cholesterol",
  "direct ldl": "LDL",
  "total protein": "Total Protein",
  albumin: "Albumin",
  calcium: "Calcium",
  sodium: "Sodium",
  potassium: "Potassium",
  "blood urea nitrogen": "BUN",
  bun: "BUN",
  urea: "Urea",
  "blood urea": "Urea",
  glucose: "FBS",
  "random blood sugar": "RBS",
  rbs: "RBS",
  "pp blood sugar": "PPBS",
  "2 hour ppbs": "PPBS",
  "pro-bnp": "Pro-BNP",
  probnp: "Pro-BNP",
  "nt-probnp": "Pro-BNP",
  "nt pro bnp": "Pro-BNP",
  "hs-crp": "hs-CRP",
  "high sensitivity crp": "hs-CRP",
  hscrp: "hs-CRP",
  iron: "Iron",
  "serum iron": "Iron",
  "total iron binding capacity": "TIBC",
  tibc: "TIBC",
  "transferrin saturation": "Transferrin Saturation",
  "% transferrin saturation": "Transferrin Saturation",
  acr: "UACR",
  "urine albumin creatinine ratio": "UACR",
  "microalbumin/creatinine": "UACR",
  wbc: "WBC",
  "white blood cells": "WBC",
  "total wbc": "WBC",
  rbc: "RBC",
  "red blood cells": "RBC",
  platelets: "Platelets",
  "platelet count": "Platelets",
  // HealthRay lab-specific variants
  "blood glucose fasting": "FBS",
  "fasting blood glucose": "FBS",
  fbg: "FBS",
  "insulin fasting": "Fasting Insulin",
  "fasting insulin": "Fasting Insulin",
  "insulin f": "Fasting Insulin",
  insulin: "Fasting Insulin",
  "homa-ir": "HOMA-IR",
  "homa - ir": "HOMA-IR",
  "homa ir": "HOMA-IR",
  "homa-b": "HOMA-Beta",
  "homa beta": "HOMA-Beta",
  "homa-beta": "HOMA-Beta",
  "c-peptide": "C-Peptide",
  "c peptide": "C-Peptide",
  triglyceride: "Triglycerides",
  "non hdl cholestrol": "Non-HDL",
  "non-hdl cholesterol": "Non-HDL",
  nonhdl: "Non-HDL",
  "glomerular filtration rate": "eGFR",
  "microalbumin/creatinine ratio": "UACR",
  "urine albumin to creatinine ratio": "UACR",
  "mean blood glucose": "Mean Blood Glucose",
  "rbc count": "RBC",
  tlc: "WBC",
  "total leucocyte count": "WBC",
  "post prandial blood sugar": "PPBS",
  "post prandial blood glucose": "PPBS",
  pp: "PPBS",
  "creatinine, serum": "Creatinine",
  "vldl cholesterol": "VLDL",
  vldl: "VLDL",
  // Hormonal / Endocrine
  "total testosterone": "Total Testosterone",
  testosterone: "Total Testosterone",
  "testosterone total": "Total Testosterone",
  "serum testosterone": "Total Testosterone",
  "free testosterone": "Free Testosterone",
  "testosterone free": "Free Testosterone",
  cortisol: "Cortisol",
  "serum cortisol": "Cortisol",
  "cortisol morning": "Cortisol",
  lh: "LH",
  "luteinizing hormone": "LH",
  "luteinising hormone": "LH",
  fsh: "FSH",
  "follicle stimulating hormone": "FSH",
  prolactin: "Prolactin",
  "serum prolactin": "Prolactin",
  amh: "AMH",
  "anti mullerian hormone": "AMH",
  "anti-mullerian hormone": "AMH",
  estradiol: "Estradiol",
  e2: "Estradiol",
  oestradiol: "Estradiol",
  progesterone: "Progesterone",
  "serum progesterone": "Progesterone",
  dheas: "DHEAS",
  "dhea-s": "DHEAS",
  "dehydroepiandrosterone sulfate": "DHEAS",
  "igf-1": "IGF-1",
  igf1: "IGF-1",
  "insulin-like growth factor": "IGF-1",
  // Metabolic extras
  "mean plasma glucose": "Mean Plasma Glucose",
  "mean blood glucose": "Mean Plasma Glucose",
  "average blood glucose": "Mean Plasma Glucose",
  "estimated average glucose": "Mean Plasma Glucose",
  fructosamine: "Fructosamine",
  "glycated albumin": "Fructosamine",
  // Hematology extras
  "indirect bilirubin": "Indirect Bilirubin",
  "unconjugated bilirubin": "Indirect Bilirubin",
  "bilirubin indirect": "Indirect Bilirubin",
  pcv: "PCV",
  "packed cell volume": "PCV",
  hematocrit: "PCV",
  haematocrit: "PCV",
  hct: "PCV",
  mcv: "MCV",
  "mean corpuscular volume": "MCV",
  mch: "MCH",
  "mean corpuscular hemoglobin": "MCH",
  "mean corpuscular haemoglobin": "MCH",
  mchc: "MCHC",
  // Inflammatory / Misc
  homocysteine: "Homocysteine",
  "serum homocysteine": "Homocysteine",
  "lipoprotein(a)": "Lipoprotein(a)",
  "lp(a)": "Lipoprotein(a)",
  lpa: "Lipoprotein(a)",
  "lipoprotein a": "Lipoprotein(a)",
  "d-dimer": "D-Dimer",
  "d dimer": "D-Dimer",
  procalcitonin: "Procalcitonin",
  pct: "Procalcitonin",
  folate: "Folate",
  "folic acid": "Folate",
  "serum folate": "Folate",
  psa: "PSA",
  "prostate specific antigen": "PSA",
};

function stripEmbeddedDate(str) {
  return str.replace(/\s*\(\d{1,2}\/\d{1,2}\/\d{2,4}\)\s*$/i, "").trim();
}

// Strips "Serum", "S.", "Sr.", "B." lab-report prefixes so variants like
// "S. Ferritin" and "Serum Calcium" collapse onto the same canonical name.
function stripReportPrefix(str) {
  return str.replace(/^(serum|plasma|s\.?|sr\.?|b\.?)\s+/i, "").trim();
}

export const getCanonical = (name) => {
  const cleaned = stripEmbeddedDate((name || "").trim())
    .replace(/[\s.]+$/, "") // strip trailing dots/spaces ("Fasting Blood Sugar ." → "Fasting Blood Sugar")
    .toLowerCase();
  if (CANONICAL_MAP[cleaned]) return CANONICAL_MAP[cleaned];
  const stripped = stripReportPrefix(cleaned);
  if (CANONICAL_MAP[stripped]) return CANONICAL_MAP[stripped];

  // Strip parenthetical suffixes — report extraction often returns names like
  // "Glycated Hemoglobin (HbA1c)" or "HbA1c (%)" that don't match the map.
  // But skip stripping when the parenthetical content is a clinical qualifier
  // that changes the test identity (e.g. "Creatinine (Urine)" ≠ "Creatinine").
  const parenMatch = stripped.match(/\(([^)]+)\)/);
  const CLINICAL_QUALIFIER = /\b(urine|random|fasting|post\s*prandial|pp\b|gtt|\d+\s*h(ou)?r)\b/i;
  const parenIsClinical = parenMatch && CLINICAL_QUALIFIER.test(parenMatch[1]);

  if (!parenIsClinical) {
    const noParens = stripped.replace(/\s*\([^)]*\)\s*/g, "").trim();
    if (noParens && noParens !== stripped && CANONICAL_MAP[noParens])
      return CANONICAL_MAP[noParens];

    // Try the content inside parentheses as a standalone lookup, e.g.
    // "Glycated Hemoglobin (HbA1c)" → try "hba1c"
    if (parenMatch) {
      const inside = parenMatch[1].trim().toLowerCase();
      if (CANONICAL_MAP[inside]) return CANONICAL_MAP[inside];
    }
  }

  return null;
};
